Test contrib-ls error detection.
Signed-off-by: Dean Wampler <dean.wampler@ibm.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,6 +5,10 @@ on:
     branches:
       - develop
     paths:
+      - ".common.mk"
+      - ".console-colors.mk"
+      - ".website.mk"
+      - "Makefile"
       - "src/**"
       - "contrib/**"
       - "examples/**"
@@ -17,6 +21,13 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Check contrib target failures
+        run: |
+          if make contrib-ls; then
+            echo "make contrib-ls should fail"
+            exit 1
+          fi
 
       - name: Install uv
         uses: astral-sh/setup-uv@v5
